// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261010165618_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("smart_blood_bank")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.BloodBank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Location", "Domain.Entities.BloodBank.Location#Location", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("location_city");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("location_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("location_longitude");
                        });

                    b.HasKey("Id");

                    b.ToTable("blood_banks", "smart_blood_bank");
                });

            modelBuilder.Entity("Domain.Entities.BloodRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BloodBankId")
                        .HasColumnType("uuid")
                        .HasColumnName("blood_bank_id");

                    b.Property<int>("BloodType")
                        .HasColumnType("integer")
                        .HasColumnName("blood_type");

                    b.Property<int>("ComponentType")
                        .HasColumnType("integer")
                        .HasColumnName("component_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("HospitalId")
                        .HasColumnType("uuid")
                        .HasColumnName("hospital_id");

                    b.Property<int>("NumberOfUnits")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_units");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("UrgencyLevel")
                        .HasColumnType("integer")
                        .HasColumnName("urgency_level");

                    b.HasKey("Id");

                    b.HasIndex("BloodBankId");

                    b.HasIndex("HospitalId");

                    b.ToTable("blood_requests", "smart_blood_bank");
                });

            modelBuilder.Entity("Domain.Entities.BloodUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BloodType")
                        .HasColumnType("integer")
                        .HasColumnName("blood_type");

                    b.Property<DateTime>("CollectionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collection_date");

                    b.Property<int>("ComponentType")
                        .HasColumnType("integer")
                        .HasColumnName("component_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CurrentBloodBankId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_blood_bank_id");

                    b.Property<Guid?>("CurrentHospitalId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_hospital_id");

                    b.Property<Guid>("DonorId")
                        .HasColumnType("uuid")
                        .HasColumnName("donor_id");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("RecipientAcceptorId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_acceptor_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<double>("VolumeMl")
                        .HasColumnType("double precision")
                        .HasColumnName("volume_ml");

                    b.HasKey("Id");

                    b.HasIndex("CurrentBloodBankId");

                    b.HasIndex("CurrentHospitalId");

                    b.HasIndex("DonorId");

                    b.HasIndex("RecipientAcceptorId");

                    b.ToTable("blood_units", "smart_blood_bank");
                });

            modelBuilder.Entity("Domain.Entities.Donation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BloodBankId")
                        .HasColumnType("uuid")
                        .HasColumnName("blood_bank_id");

                    b.Property<Guid>("BloodUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("blood_unit_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("DonationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("donation_date");

                    b.Property<Guid>("DonorId")
                        .HasColumnType("uuid")
                        .HasColumnName("donor_id");

                    b.Property<Guid?>("HospitalId")
                        .HasColumnType("uuid")
                        .HasColumnName("hospital_id");

                    b.Property<DateTime>("NextEligibleDonationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_eligible_donation_date");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("BloodBankId");

                    b.HasIndex("BloodUnitId");

                    b.HasIndex("DonorId");

                    b.HasIndex("HospitalId");

                    b.ToTable("donations", "smart_blood_bank");
                });

            modelBuilder.Entity("Domain.Entities.DonationAppointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BloodBankId")
                        .HasColumnType("uuid")
                        .HasColumnName("blood_bank_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BloodBankId");

                    b.HasIndex("UserId");

                    b.ToTable("donation_appointments", "smart_blood_bank");
                });

            modelBuilder.Entity("Domain.Entities.DonationCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActualUnits")
                        .HasColumnType("integer")
                        .HasColumnName("actual_units");

                    b.Property<Guid>("BloodBankId")
                        .HasColumnType("uuid")
                        .HasColumnName("blood_bank_id");

                    b.Property<int>("BloodType")
                        .HasColumnType("integer")
                        .HasColumnName("blood_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TargetUnits")
                        .HasColumnType("integer")
                        .HasColumnName("target_units");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("BloodBankId");

                    b.ToTable("donation_campaigns", "smart_blood_bank");
                });

            modelBuilder.Entity("Domain.Entities.Hospital", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Location", "Domain.Entities.Hospital.Location#Location", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("location_city");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("location_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("location_longitude");
                        });

                    b.HasKey("Id");

                    b.ToTable("hospitals", "smart_blood_bank");
                });

            modelBuilder.Entity("Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at_utc");

                    b.Property<Guid?>("RecipientBloodBankId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_blood_bank_id");

                    b.Property<Guid?>("RecipientHospitalId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_hospital_id");

                    b.Property<Guid?>("RecipientUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_user_id");

                    b.Property<Guid?>("RelatedBloodRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_blood_request_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("RecipientBloodBankId");

                    b.HasIndex("RecipientHospitalId");

                    b.HasIndex("RecipientUserId");

                    b.HasIndex("RelatedBloodRequestId");

                    b.ToTable("notifications", "smart_blood_bank");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BloodBankId")
                        .HasColumnType("uuid")
                        .HasColumnName("blood_bank_id");

                    b.Property<int>("BloodType")
                        .HasColumnType("integer")
                        .HasColumnName("blood_type");

                    b.Property<int>("BloodUnitsBalance")
                        .HasColumnType("integer")
                        .HasColumnName("blood_units_balance");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<Guid?>("HospitalId")
                        .HasColumnType("uuid")
                        .HasColumnName("hospital_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("NationalNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("national_number");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Location", "Domain.Entities.User.Location#Location", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("location_city");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("location_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("location_longitude");
                        });

                    b.HasKey("Id");

                    b.HasIndex("BloodBankId");

                    b.HasIndex("HospitalId");

                    b.ToTable("users", "smart_blood_bank");
                });

            modelBuilder.Entity("Domain.Entities.WalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<Guid?>("BloodRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("blood_request_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DonationId")
                        .HasColumnType("uuid")
                        .HasColumnName("donation_id");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BloodRequestId");

                    b.HasIndex("DonationId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("UserId");

                    b.ToTable("wallet_transactions", "smart_blood_bank");
                });

            modelBuilder.Entity("Domain.Entities.BloodRequest", b =>
                {
                    b.HasOne("Domain.Entities.BloodBank", "BloodBank")
                        .WithMany("FulfilledRequests")
                        .HasForeignKey("BloodBankId");

                    b.HasOne("Domain.Entities.Hospital", "Hospital")
                        .WithMany("BloodRequests")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodBank");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("Domain.Entities.BloodUnit", b =>
                {
                    b.HasOne("Domain.Entities.BloodBank", "CurrentBloodBank")
                        .WithMany("StoredUnits")
                        .HasForeignKey("CurrentBloodBankId");

                    b.HasOne("Domain.Entities.Hospital", "CurrentHospital")
                        .WithMany("StoredUnits")
                        .HasForeignKey("CurrentHospitalId");

                    b.HasOne("Domain.Entities.User", "Donor")
                        .WithMany("DonatedUnits")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "RecipientAcceptor")
                        .WithMany("ReceivedUnits")
                        .HasForeignKey("RecipientAcceptorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentBloodBank");

                    b.Navigation("CurrentHospital");

                    b.Navigation("Donor");

                    b.Navigation("RecipientAcceptor");
                });

            modelBuilder.Entity("Domain.Entities.Donation", b =>
                {
                    b.HasOne("Domain.Entities.BloodBank", "BloodBank")
                        .WithMany()
                        .HasForeignKey("BloodBankId");

                    b.HasOne("Domain.Entities.BloodUnit", "BloodUnit")
                        .WithMany()
                        .HasForeignKey("BloodUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "Donor")
                        .WithMany()
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Hospital", "Hospital")
                        .WithMany()
                        .HasForeignKey("HospitalId");

                    b.Navigation("BloodBank");

                    b.Navigation("BloodUnit");

                    b.Navigation("Donor");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("Domain.Entities.DonationAppointment", b =>
                {
                    b.HasOne("Domain.Entities.BloodBank", "BloodBank")
                        .WithMany()
                        .HasForeignKey("BloodBankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodBank");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.DonationCampaign", b =>
                {
                    b.HasOne("Domain.Entities.BloodBank", "BloodBank")
                        .WithMany()
                        .HasForeignKey("BloodBankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodBank");
                });

            modelBuilder.Entity("Domain.Entities.Notification", b =>
                {
                    b.HasOne("Domain.Entities.BloodBank", null)
                        .WithMany()
                        .HasForeignKey("RecipientBloodBankId");

                    b.HasOne("Domain.Entities.Hospital", null)
                        .WithMany()
                        .HasForeignKey("RecipientHospitalId");

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("RecipientUserId");

                    b.HasOne("Domain.Entities.BloodRequest", null)
                        .WithMany()
                        .HasForeignKey("RelatedBloodRequestId");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.BloodBank", "BloodBank")
                        .WithMany("Staff")
                        .HasForeignKey("BloodBankId");

                    b.HasOne("Domain.Entities.Hospital", "Hospital")
                        .WithMany("Staff")
                        .HasForeignKey("HospitalId");

                    b.Navigation("BloodBank");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("Domain.Entities.WalletTransaction", b =>
                {
                    b.HasOne("Domain.Entities.BloodRequest", "BloodRequest")
                        .WithMany("WalletTransactions")
                        .HasForeignKey("BloodRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Donation", "Donation")
                        .WithMany()
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BloodRequest");

                    b.Navigation("Donation");

                    b.Navigation("Receiver");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.BloodBank", b =>
                {
                    b.Navigation("FulfilledRequests");

                    b.Navigation("Staff");

                    b.Navigation("StoredUnits");
                });

            modelBuilder.Entity("Domain.Entities.BloodRequest", b =>
                {
                    b.Navigation("WalletTransactions");
                });

            modelBuilder.Entity("Domain.Entities.Hospital", b =>
                {
                    b.Navigation("BloodRequests");

                    b.Navigation("Staff");

                    b.Navigation("StoredUnits");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("DonatedUnits");

                    b.Navigation("ReceivedUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
