services:
  flutter:
    build:
      context: ./ZaidFlutterCode
      dockerfile: Dockerfile
      target: runtime
    container_name: bloodbank_flutter_web
    ports:
      - "8080:80"
    restart: unless-stopped

  postgres:
    image: postgres:17
    container_name: bloodbank_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: smart_blood_bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
