services:
  flutter:
    build:
      context: ./ZaidFlutterCode
      dockerfile: Dockerfile
      target: runtime
    container_name: bloodbank_flutter_web
    ports:
      - "8080:80"
    restart: unless-stopped
